version: "3"
services:
  express-app:
    build: .
    ports:
      - "8080:3000"
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - api-mongo-db:/data/db
volumes:
  api-mongo-db:
